
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

import os

juce_env = env.Clone()

# Check that JUCE submodule is initialized
# Use srcnode() to get the source directory path, not the build variant directory
juce_modules_path = env.Dir('juce/modules').srcnode().abspath
if not os.path.isdir(juce_modules_path):
    print("\n" + "="*80)
    print("ERROR: JUCE submodule not initialized!")
    print("="*80)
    print("The lib_juce/juce submodule is missing or not properly initialized.")
    print("Expected path: " + juce_modules_path)
    print("\nTo fix this, run:")
    print("  git submodule update --init --recursive")
    print("\nThis will download and initialize all required submodules.")
    print("="*80 + "\n")
    Exit(1)

me = env.Dir('.').abspath

juce_env.Append(CPPPATH='juce/modules')
juce_env.Append(CPPPATH='juce/modules/juce_audio_processors/format_types/VST3_SDK')

# LV2 hosting: vendored lilv/sord/serd/sratom amalgamation expects these on the
# include path (mirrors juce/extras/Build/CMake/JUCEModuleSupport.cmake).
_lv2_base = 'juce/modules/juce_audio_processors/format_types/LV2_SDK'
for _sub in ('', '/lv2', '/serd', '/sord', '/sord/src', '/sratom', '/lilv', '/lilv/src'):
    juce_env.Append(CPPPATH=_lv2_base + _sub)

# Common JUCE module names (platform-specific extensions added below)
juce_common_modules = [
    'juce_audio_basics',
    'juce_audio_devices', 
    'juce_audio_formats',
    'juce_audio_processors',
    'juce_audio_utils',
    'juce_core',
    'juce_cryptography',
    'juce_data_structures',
    'juce_events',
    'juce_graphics',
    'juce_gui_basics',
    'juce_gui_extra'
]

# Common additional files (platform-independent)
# SheenbidiWrapper.c is our (required) wrapper araound - juce/modules/juce_graphics/unicode/sheenbidi/Source/SheenBidi.c
juce_common_files = Split("""
    juce/modules/juce_core/juce_core_CompilationTime.cpp
    juce/modules/juce_graphics/juce_graphics_Harfbuzz.cpp
    SheenbidiWrapper.c
""")

# Common compiler flags
juce_common_flags = '-DNDEBUG -DJUCE_DLL_BUILD -DJUCE_GLOBAL_MODULE_SETTINGS_INCLUDED=1'

if env['IS_WINDOWS']:
    # Windows uses .cpp extension
    juce_files = [f'juce/modules/{mod}/{mod}.cpp' for mod in juce_common_modules] + juce_common_files
    juce_env.Append(CCFLAGS=f'/D "WINDOWS=1" /D "_LIB" /D "WIN32" /D "_WINDOWS" {juce_common_flags} /FI AppConfig.h /arch:SSE2')
    juce_env.Append(LINKFLAGS="/nodefaultlib:libcmt.lib")
    juce_env.Append(LINKFLAGS='WS2_32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib')
    juce_env.Append(LINKFLAGS='advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib')
    juce_env.Append(LINKFLAGS='odbccp32.lib wininet.lib shlwapi.lib version.lib imm32.lib winmm.lib ')
    juce_env.Append(LINKFLAGS='Dbghelp.lib')

if env['IS_LINUX']:
    # Linux uses .cpp extension
    juce_files = [f'juce/modules/{mod}/{mod}.cpp' for mod in juce_common_modules] + juce_common_files
    # LV2 hosting: compile vendored lilv/sord/serd/sratom amalgamation TU.
    juce_files += ['juce/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp']
    # JUCE is third-party; don't promote its warnings to errors (the LV2 amalgamation
    # in particular redefines _POSIX_C_SOURCE which glibc already sets via -D_GNU_SOURCE).
    juce_env.Append(CCFLAGS=f'-Wno-error -Wno-unused-variable -Wno-sign-compare -DLINUX=1 {juce_common_flags} -include AppConfig.h')
    juce_env.Append(CPPPATH='/usr/include/freetype2')
    juce_env.Append(LIBS=Split('X11 freetype Xext asound'))

    # LADSPA hosting (optional): only enabled if <ladspa.h> is installed
    # (e.g. `apt install ladspa-sdk`). When absent we silently build without it.
    if any(os.path.exists(p) for p in ('/usr/include/ladspa.h',
                                       '/usr/local/include/ladspa.h')):
        juce_env.Append(CCFLAGS='-DJUCE_PLUGINHOST_LADSPA=1')
        print("lib_juce: LADSPA plugin hosting enabled")
    else:
        print("lib_juce: LADSPA plugin hosting disabled (install ladspa-sdk to enable)")

if env['IS_MACOSX']:
    # macOS uses .mm extension (Objective-C++)
    juce_files = [f'juce/modules/{mod}/{mod}.mm' for mod in juce_common_modules] + juce_common_files
    juce_env.Append(CCFLAGS=f'-Wno-unused-variable {juce_common_flags} -DHAVE_CORETEXT=1 -include AppConfig.h')
    juce_env.Append(LINKFLAGS='-framework CoreAudio -framework CoreMIDI -framework AudioUnit -framework IOKit')
    juce_env.Append(LINKFLAGS='-framework Cocoa -framework Carbon -framework AppKit -framework QuartzCore')
    juce_env.Append(LINKFLAGS='-framework CoreFoundation -framework CoreAudioKit -framework AudioToolbox')
    juce_env.Append(LINKFLAGS='-framework Security')  # Required for JUCE 8 code signing checks

juce_env.Append(CPPPATH=me)
juce_libraries = []  # No separate VST3 lib needed since compiled statically
if env['IS_MACOSX'] or env['IS_LINUX'] or env['IS_WINDOWS']:
    juce_env.Append(LIBPATH=['$BINRUNDIR'])
juce_env.PiSharedLibrary('pijuce',juce_files,libraries=juce_libraries,package='eigend')

ejuce_env = env.Clone()
ejuce_env.Append(CPPPATH='juce/modules')
ejuce_files = Split('ejuce.cpp ejuce_laf.cpp')
ejuce_libraries = Split('pijuce pia pic')
ejuce_env.PiSharedLibrary('ejuce',ejuce_files,libraries=ejuce_libraries,package='eigend')

epython_env = env.Clone()
epython_files = Split('epython.cpp')
epython_libraries = Split('pia pie pic')
epython_env.PiSharedLibrary('epython',epython_files,libraries=epython_libraries,package='eigend')
